phonebook_app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash
from flask_login import UserMixin, LoginManager
from flask_marshmallow import Marshmallow
import uuid, secrets

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    username = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)
    token = db.Column(db.String, default='', unique=True)
    join_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    phone_number = db.Column(db.Integer, nullable=True)

    def __init__(self, username, email, phone_number, password):
        self.id =  self.set_id()
        self.username = username
        self.email = email
        self.phone_number = phone_number
        self.password = self.set_password(password)
        self.token = self.set_token(32)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        return generate_password_hash(password)

    def set_token(self, length):
        return secrets.token_hex(length)

    def __repr__(self):
        return f'username: {self.username}, email: {self.email} was added to Users'

class Address(db.Model):
    id = db.Column(db.String, primary_key=True)
    street = db.Column(db.String)
    city = db.Column(db.String)
    state = db.Column(db.String)
    zipcode = db.Column(db.Integer)
    user_token = db.Column(db.String, db.ForeignKey('user.token'))

    def __init__(self, street, city, state, zipcode, user_token):
        self.id = self.set_id()
        self.street = street
        self.city = city
        self.state = state
        self.zipcode = zipcode
        self.user_token = user_token

    def set_id(self):
        return str(uuid.uuid4())

    def __repr__(self):
        return f'The address {self.street}, {self.city}, {self.state} {self.zipcode} was added'

class AddressSchema(ma.Schema):
    class Meta:
        fields = ['id', 'street', 'city', 'state', 'zipcode']
address_schema = AddressSchema()
addresses_schema = AddressSchema(many=True)

phonebook_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TelField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Email, Length, EqualTo, Optional

class LoginForm(FlaskForm):
    email = StringField('email:', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField()

class RegisterForm(FlaskForm):
    username = StringField('username:', validators=[DataRequired(), Length(min=3, max=40)])
    email = StringField('email:', validators=[DataRequired(), Email()])
    phone_number = TelField('phone number:', validators=[DataRequired()])
    password = PasswordField('new password:', validators=[DataRequired(), EqualTo('confirm', message='passwords are not matching')])
    confirm = PasswordField('confirm password:', validators=[DataRequired(), EqualTo('password', message='passwords are not matching')])
    submit = SubmitField()

class AddressForm(FlaskForm):
    street = StringField('street:', validators=[DataRequired()])
    city = StringField('city:', validators=[DataRequired()])
    state = StringField('state:', validators=[DataRequired()])
    zipcode = IntegerField('zip code:', validators=[Optional()])
    submit = SubmitField()

phonebook_app/__init__.py
from flask import Flask
from config import Config
from flask_migrate import Migrate
from flask_cors import CORS

from .site.routes import site
from .auth.routes import auth

from .helpers import JSONEncoder
from .models import db as root_db, login_manager, ma

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)

app.config.from_object(Config)
root_db.init_app(app)
migrate = Migrate(app, root_db)
ma.init_app(app)

login_manager.init_app(app)
login_manager.login_view = 'auth.login'

app.json_encoder = JSONEncoder

phonebook_app/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from ..forms import AddressForm
from ..models import Address, db

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    my_address = AddressForm()
    try:
        if request.method == 'POST' and my_address.validate_on_submit():
            street = my_address.street.data
            city = my_address.city.data
            state = my_address.state.data
            zipcode = my_address.zipcode.data
            user_token = current_user.token

            address = Address(street, city, state, zipcode, user_token)
            db.session.add(address)
            db.session.commit()

            return redirect(url_for('site.profile'))
    except:
        raise Exception('Something aint right')

    current_user_token = current_user.token
    addresses = Address.query.filter_by(user_token=current_user_token)

    return render_template('profile.html', form=my_address, addresses=addresses, our_user=current_user)

phonebook_app/templates/address_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        <fieldset id="street-field" style="border: none;">
            {{ form.street.label(class='text-white text-sm') }}
            {{ form.street(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Street Address: ') }}
        </fieldset>
        <fieldset id="city-field" style="border: none;">
            {{ form.city.label(class='text-white text-sm') }}
            {{ form.city(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='City: ') }}
        </fieldset>
        <fieldset id="state-field" style="border: none;">
            {{ form.state.label(class='text-white text-sm') }}
            {{ form.state(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='State: ') }}
        </fieldset>
        <fieldset id="zipcode-field" style="border: none;">
            {{ form.zipcode.label(class='text-white text-sm') }}
            {{ form.zipcode(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Zip Code: ') }}
        </fieldset>
    </div>
    {{ form.submit(class='w-full cursor-pointer self-end mt-8 px-5 py-2 rounded-full bg-gradient-to-t from-pink-500 to-yellow-500 hover:from-green-400 hover:to-blue-500', value='Add') }}
</form>

phonebook_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            corePlugins: {
                preflight: false,
            },
        }
    </script>
    <title>Phonebook App</title>
</head>
<body class="bg-slate-800">
    <div class="text-3xl">
        <nav class="flex justify-center divide-x gap-12">
            <a class="text-emerald-300" href="{{ url_for('site.home') }}">Home</a>
            {% if current_user.is_authenticated %}
                <a class="text-emerald-300" href="{{ url_for('auth.logout') }}">Logout</a>
                <a class="text-emerald-300" href="{{ url_for('site.profile') }}">Profile</a>
            {% else %}
                <a class="text-emerald-300" href="{{ url_for('auth.register') }}">Register</a>
                <a class="text-emerald-300" href="{{ url_for('auth.login') }}">Login</a>
            {% endif %}
        </nav>
    </div>

    {% block content %}
    {% endblock content %}
</body>
</html>

phonebook_app/templates/login_form.html
<form method="POST">
  {{ form.hidden_tag() }}
  <div class="text-slate-950">
      <fieldset id="email-field" style="border: none;">
          {{ form.email.label(class='text-white') }}
          {{ form.email(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='username@example.com') }}
      </fieldset>
      <fieldset id="password-field" style="border: none;">
          {{ form.password.label(class='text-white') }}
          {{ form.password(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Enter password') }}
      </fieldset>
  </div>
  {{ form.submit(class='w-full cursor-pointer self-end mt-8 px-5 py-2 rounded-full bg-gradient-to-t from-green-400 to-purple-500 hover:from-pink-500 hover:to-yellow-500', value='Login') }}
</form>

phonebook_app/templates/register_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        <fieldset id="username-field" style="border: none;">
            {{ form.username.label(class='text-white text-sm') }}
            {{ form.username(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Create username: ') }}
        </fieldset>
        <fieldset id="email-field" style="border: none;">
            {{ form.email.label(class='text-white text-sm') }}
            {{ form.email(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Your email: ') }}
        </fieldset>
        <fieldset id="phone_number-field" style="border: none;">
            {{ form.phone_number.label(class='text-white text-sm') }}
            {{ form.phone_number(class='mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Your phone number: ') }}
        </fieldset>
        <fieldset id="password-field" class="flex mt-2" style="border: none;">
            <div class="flex flex-col">
                {{ form.password.label(class='text-white text-sm') }}
                {{ form.password(class='block w-fit px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Create password: ') }}
            </div>
            <div class="flex flex-col">
                {{ form.confirm.label(class='text-white text-sm') }}
                {{ form.confirm(class='block w-fit px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500', placeholder='Create password: ') }}
            </div>
        </fieldset>
    </div>
    {{ form.submit(class='w-full cursor-pointer self-end mt-8 px-5 py-2 rounded-full bg-gradient-to-t from-pink-500 to-yellow-500 hover:from-green-400 hover:to-blue-500', value='Register') }}
</form>